### ISSUE TITLE
Improve UI clarity

### ISSUE THREAD

**Issue by LiptonLeon** [Memory-Leak-Games/Project-InPostors#150]
- [ ] Better product icons
- [x] Show amount of items in factory

**Comment by Erulathra** [comment]
- [ ] Add progress for generators (mine etc) - UI
or
- [ ] Make generator items always available - Gameplay

**Comment by LiptonLeon** [comment]
UI has been moved from Entities to seperate components, ex. Factory has FactoryUI component

**Comment by LiptonLeon** [comment]
Pull request #193
